# Generated by Django 3.0.5 on 2020-04-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
