# Generated by Django 3.0.5 on 2020-04-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderrequest_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='complete',
            field=models.BooleanField(),
        ),
    ]
