# Generated by Django 3.0.5 on 2020-04-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200413_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
